IMDB dataset having 50K movie reviews for natural language processing or Text analytics. 
This is a dataset for binary sentiment classification containing substantially more data than previous benchmark 
datasets.

#### Loading the Dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./Data/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.iloc[0,:]

review       One of the other reviewers has mentioned that ...
sentiment                                             positive
Name: 0, dtype: object

#### Making the Corpus

In [4]:
df = df.drop(columns="sentiment",axis=1)
df.head()

                                              review
0  One of the other reviewers has mentioned that ...
1  A wonderful little production. <br /><br />The...
2  I thought this was a wonderful way to spend ti...
3  Basically there's a family where a little boy ...
4  Petter Mattei's "Love in the Time of Money" is...

In [5]:
df = df.iloc[:1000,0]
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: review
Non-Null Count  Dtype
--------------  -----
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [6]:
corpus = list(df)

In [7]:
len(corpus)

1000

In [8]:
alpha_corpus = []
punctuations = ['/','.', ',', '!', '?', ';', ':','\\']
for document in corpus:
    document = ''.join(ch for ch in document if ch not in punctuations) ## join without space
    lower_words = [word.lower() for word in document.split()]
    alpha_words = [word for word in lower_words if word.isalpha()]
    normalised_document = ' '.join(alpha_words)
    alpha_corpus.append(normalised_document)

In [9]:
alpha_corpus[0]

'one of the other reviewers has mentioned that after watching just oz episode be hooked they are right as this is exactly what happened with first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far would say the main appeal of the show is due to the fact that it goes where other shows dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz mess around the first episode i ever saw struck me as so nasty it was surreal i say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice guards be sold out for a nickel inmates kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [10]:
tokenised_corpus = []
for document in alpha_corpus:
    tokens = [word for word in document.split()]
    tokenised_corpus.append(tokens)
tokenised_corpus[0]

['one',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 'oz',
 'episode',
 'be',
 'hooked',
 'they',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'go',
 'trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'this',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'is',
 'called',
 'oz',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'it',
 'focuses',
 'mainly',
 'on',
 'emerald',
 'city',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 'em',
 'city',
 'is',
 'home',
 'to',
 'manyaryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'and',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceoz',
 'mess',
 'around',
 'the',
 'first',
 'episode',
 'i',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 'i',
 'say',
 'i',
 'was',
 'ready',
 'for',
 'it',
 'but',
 'as',
 'i',
 'watched',
 'more',
 'i',
 'developed',
 'a',
 'taste',
 'for',
 'oz',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 'not',
 'just',
 'violence',
 'but',
 'injustice',
 'guards',
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 'inmates',
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'watching',
 'oz',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewingthats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side']

In [11]:
from nltk.corpus import stopwords

In [12]:
sw = stopwords.words(fileids='english')
sw

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [13]:
nostop_corpus = []
for document in tokenised_corpus:
    nostop = [word for word in document if word not in sw]
    nostop_corpus.append(nostop)
nostop_corpus[0]

['one',
 'reviewers',
 'mentioned',
 'watching',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly',
 'happened',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'manyaryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceoz',
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'guards',
 'sold',
 'nickel',
 'inmates',
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewingthats',
 'get',
 'touch',
 'darker',
 'side']

In [14]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [15]:
stemmed_corpus = []
for document in nostop_corpus:
    stemmed = [ps.stem(word) for word in document if word not in sw]
    stemmed_corpus.append(stemmed)
len(stemmed_corpus), len(stemmed_corpus[0])

(1000, 156)

In [16]:
vocabulary = []
for document in stemmed_corpus:
    vocabulary += document
len(vocabulary)

107855

In [17]:
vocabulary = list(set(vocabulary))
len(vocabulary)

11960

Converting the corpus into binary BOW vector of size mXn, where m=1000 (number of reviews 
documents) and n is the number of unique terms obtained from the 1000 documents. Each ij th entry 
of the vector is a binary value which is 1 if the jth term is present in ith review else 0.

In [18]:
bow = []
for document in stemmed_corpus:
    dic = {}
    for word in vocabulary:
        dic[word] = 1 if word in document else 0
    bow.append(dic)

In [19]:
bow[0]["violenc"]

1

In [20]:
matrix = {word: {w: 0 for w in vocabulary} for word in vocabulary}
matrix["violenc"]["violenc"]

0

In [21]:
print(len(stemmed_corpus))
print(stemmed_corpus[:2])

1000
[['one', 'review', 'mention', 'watch', 'oz', 'episod', 'hook', 'right', 'exactli', 'happen', 'first', 'thing', 'struck', 'oz', 'brutal', 'unflinch', 'scene', 'violenc', 'set', 'right', 'word', 'go', 'trust', 'show', 'faint', 'heart', 'timid', 'show', 'pull', 'punch', 'regard', 'drug', 'sex', 'violenc', 'hardcor', 'classic', 'use', 'call', 'oz', 'nicknam', 'given', 'oswald', 'maximum', 'secur', 'state', 'penitentari', 'focus', 'mainli', 'emerald', 'citi', 'experiment', 'section', 'prison', 'cell', 'glass', 'front', 'face', 'inward', 'privaci', 'high', 'agenda', 'em', 'citi', 'home', 'manyaryan', 'muslim', 'gangsta', 'latino', 'christian', 'italian', 'irish', 'moreso', 'scuffl', 'death', 'stare', 'dodgi', 'deal', 'shadi', 'agreement', 'never', 'far', 'would', 'say', 'main', 'appeal', 'show', 'due', 'fact', 'goe', 'show', 'dare', 'forget', 'pretti', 'pictur', 'paint', 'mainstream', 'audienc', 'forget', 'charm', 'forget', 'romanceoz', 'mess', 'around', 'first', 'episod', 'ever', 'saw', 'struck', 'nasti', 'surreal', 'say', 'readi', 'watch', 'develop', 'tast', 'oz', 'got', 'accustom', 'high', 'level', 'graphic', 'violenc', 'violenc', 'injustic', 'guard', 'sold', 'nickel', 'inmat', 'kill', 'order', 'get', 'away', 'well', 'manner', 'middl', 'class', 'inmat', 'turn', 'prison', 'bitch', 'due', 'lack', 'street', 'skill', 'prison', 'watch', 'oz', 'may', 'becom', 'comfort', 'uncomfort', 'viewingthat', 'get', 'touch', 'darker', 'side'], ['wonder', 'littl', 'product', 'film', 'techniqu', 'fashion', 'give', 'comfort', 'sometim', 'discomfort', 'sens', 'realism', 'entir', 'piec', 'actor', 'extrem', 'well', 'michael', 'sheen', 'got', 'voic', 'pat', 'truli', 'see', 'seamless', 'edit', 'guid', 'refer', 'diari', 'entri', 'well', 'worth', 'watch', 'terrificli', 'written', 'perform', 'piec', 'master', 'product', 'one', 'great', 'comedi', 'life', 'realism', 'realli', 'come', 'home', 'littl', 'thing', 'fantasi', 'guard', 'rather', 'use', 'tradit', 'techniqu', 'remain', 'solid', 'disappear', 'play', 'knowledg', 'sens', 'particularli', 'scene', 'concern', 'orton', 'halliwel', 'set', 'flat', 'mural', 'decor', 'everi', 'terribl', 'well', 'done']]

In [22]:
ws = 3
for document in stemmed_corpus:
    for i in range(len(document)):
       word = document[i]
       start = max(0, i - ws)
       end = min(len(document), i + ws + 1)

       for j in range(i-1, start-1, -1):
         matrix[word][document[j]] += 1

       for j in range(i+1, end):
          matrix[word][document[j]] += 1

In [23]:
import numpy as np
mat = np.array(pd.DataFrame(matrix))

In [24]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=100)
truncated = svd.fit_transform(mat)

In [25]:
np.array(truncated).shape

(11960, 100)

In [26]:
truncated

array([[ 1.33899581e+00,  1.16804430e-01, -4.78679333e-01, ...,
         2.17498841e-01, -2.11577401e-01,  1.26391776e-01],
       [ 5.59822940e-02,  3.80014808e-02, -5.46786493e-03, ...,
        -1.13400400e-01, -2.23979764e-02, -8.86698629e-02],
       [ 2.55686178e+02, -6.15068456e+01,  1.18286523e+01, ...,
        -8.14526172e-01, -4.17400182e-01, -1.06731017e+00],
       ...,
       [ 2.90127292e-01,  2.51700064e-01, -4.66326002e-03, ...,
        -1.40283483e-02, -4.50464615e-02,  6.42128295e-02],
       [ 3.15739149e-02,  1.62642097e-02, -2.79087680e-02, ...,
         3.08082094e-03,  7.46478510e-03,  1.22706411e-02],
       [ 8.01517263e-01,  1.53380829e-02, -3.28628951e-01, ...,
        -6.30164896e-02, -9.46707499e-02, -2.56760687e-01]])